# Vector and Matrix Multiplication

In [1]:
import pandas as pd
import numpy as np

### Warmup


Without using NumPy, write a python function that takes in a list of lists, and returns a list of lists of the same dimensions, where all of the elements are multiplied by 2.

In [2]:
lol = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [3]:
len(lol)

4

In [4]:
def warmup(lol):
    """Solution 1:
       2 nested for loops
       
       INDENTATION IS SUPER IMPORTANT!
    """
    final_list = []
    for sublist in lol:
        new_sublist = []
        for num in sublist:
            new_sublist.append(num*2)
         
        final_list.append(new_sublist)

    return final_list  

In [5]:
#"for each" loop
for let in list('abcd'):
    print(let)

a
b
c
d


In [6]:
#"classic for loop"
letters = list('abcd')
for i in range(0, len(letters)):
    print(letters[i])

a
b
c
d


In [7]:
def warmup2(lol):
    """Solution 1:
       2 nested for loops
       
       Using Indexing....harder....
    """
    final_list = []
    for i in range(0, len(lol)):
        new_sublist = []
        for j in range(0, len(lol[i])):
            new_sublist.append(lol[i][j]*2)
         
        final_list.append(new_sublist)

    return final_list 

In [8]:
warmup2(lol)

[[2, 4, 6], [8, 10, 12], [14, 16, 18], [20, 22, 24]]

In [9]:
def warmup3(lol):
    
    """Solution 2:
       2 nested for loops, but the second one uses a list comprehension.
    """
    new_lol = []
    for sublist in lol:
        new_lol.append([2*x for x in sublist])
    return new_lol

In [10]:
np.array(lol)*2
#Numpy does "element-wise" arithmetic for you!
#So more crazy nested for-loops.

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [11]:
triple_nested = np.random.randint(low=1, high=10, size=(3, 3, 3))

In [12]:
triple_nested #in python, you would need 3 FOR LOOPS to perform arithmetic on this....ouch!!

array([[[5, 1, 8],
        [2, 4, 1],
        [8, 8, 9]],

       [[1, 2, 9],
        [8, 6, 9],
        [5, 2, 1]],

       [[4, 3, 1],
        [9, 4, 3],
        [9, 7, 8]]])

In [13]:
triple_nested*2 #one-liner in numpy

array([[[10,  2, 16],
        [ 4,  8,  2],
        [16, 16, 18]],

       [[ 2,  4, 18],
        [16, 12, 18],
        [10,  4,  2]],

       [[ 8,  6,  2],
        [18,  8,  6],
        [18, 14, 16]]])

Difference between Python Lists and NumPy Arrays:
- Python lists are built-in data structures, NumPy Arrays need to be imported 
- Python lists are general purpose containers
- NumPy arrays contain elements of the SAME TYPE. Usually floating-point numbers.
    - this is advantageous because when doing calculations, python doesn't need to waste time checking the data type of each individual element.
    - in memory, elements of an array are stored physically next to each other.
- NumPy is built on top of the array in C. (SUPER FAST LANGUAGE)

In [14]:
['cat', 'dog', 1, {'cat':'Katze'}, 1.5] 
#lists can contain elements of different types

['cat', 'dog', 1, {'cat': 'Katze'}, 1.5]

In [15]:
%timeit warmup(lol)

900 ns ± 9.95 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [16]:
lol_array = np.array(lol)

In [17]:
%timeit lol_array*2

562 ns ± 8.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In Summary:
- Numpy is easier syntactically to do array-like arithmetic
- Numpy is FASTER

---

### Dot Product: Vector * Vector -> Scalar

In [18]:
df = pd.DataFrame({
    'prices': [1.99, 0.99, 5.99],
    'Ada': [2, 3, 1]
},
    index=['banana', 'apple', 'coffee'])
df

prices  Ada
banana    1.99    2
apple     0.99    3
coffee    5.99    1

Ada buys 2 bananas, 3 apples, and 1 bag of coffee. What is the total cost of the basket?

In [19]:
(df['prices'] * df['Ada']).sum()

12.94

A "Vector" is a uni-dimensional numpy array.
- When taking the "dot-product" ("inner-product") of 2 vectors, the result is a *scalar*.

In [20]:
np.dot(df['prices'], df['Ada'])

12.940000000000001

In [21]:
(1.99 * 2) + (0.99 * 3) + (5.99 * 1)

12.94

---

### Vector * Matrix -> Vector

Now we have 2 customers; what is the basket cost of each customer?

In [27]:
df['Bob'] = [0, 9, 1]

In [28]:
df

prices  Ada  Bob
banana    1.99    2    0
apple     0.99    3    9
coffee    5.99    1    1

In [29]:
np.dot(df['prices'], df['Ada']), np.dot(df['prices'], df['Bob'])

(12.940000000000001, 14.9)

In [30]:
price_vector = df['prices'] #Series
user_matrix = df[['Ada', 'Bob']] #DataFrame

In [31]:
df['prices'].values # (3,) vector (flat hierarchy)

array([1.99, 0.99, 5.99])

In [32]:
df[['prices']].values #(3, 1) matrix (nested hierarchy)

array([[1.99],
       [0.99],
       [5.99]])

In [33]:
user_matrix.shape

(3, 2)

In [34]:
np.dot(price_vector, user_matrix)

array([12.94, 14.9 ])

In [35]:
price_vector.dot(user_matrix) #alternative

Ada    12.94
Bob    14.90
Name: prices, dtype: float64

In [36]:
# np.dot(user_matrix, price_vector)
### ORDER MATTERS!!!!

---

### Matrix * Matrix -> Matrix (Matrix Multiplication)

![matrix_multiplication_board.jpeg](matrix_multiplication_board.jpeg)

Now you have two customers and four supermarkets.

Given that every supermarket has different prices, what is the basket cost for each customer for each supermarket?

In [37]:
shops = pd.DataFrame({
    'rewe': [1.99, 0.99, 5.99],
    'lidl': [0.99, 0.89, 4.99],
    'aldi': [0.99, 1.29, 4.99],
    'edeka': [1.89, 1.59, 3.99]
},   
    index=['banana', 'apple', 'coffee']
)


In [38]:
shops

rewe  lidl  aldi  edeka
banana  1.99  0.99  0.99   1.89
apple   0.99  0.89  1.29   1.59
coffee  5.99  4.99  4.99   3.99

In [39]:
shops.shape #3 rows, 4 columns

(3, 4)

In [40]:
user_matrix

Ada  Bob
banana    2    0
apple     3    9
coffee    1    1

In [41]:
user_matrix.shape

(3, 2)

We cannot do (3, 2) * (3, 4)

We CAN do (2, 3) * (3, 4) ---> The inner values MUST be the same!!!

This results in a (2, 4)!

- ALWAYS MAKE SURE THAT THE INNER DIMENSIONS ARE LINED UP!

In [42]:
# user_matrix.values.reshape(2, 3)

In [43]:
user_matrix.transpose()

# OR user_matrix.T

banana  apple  coffee
Ada       2      3       1
Bob       0      9       1

In [44]:
np.dot(user_matrix.transpose(), shops)

array([[12.94,  9.64, 10.84, 12.54],
       [14.9 , 13.  , 16.6 , 18.3 ]])

In [45]:
user_matrix.transpose().dot(shops)

rewe   lidl   aldi  edeka
Ada  12.94   9.64  10.84  12.54
Bob  14.90  13.00  16.60  18.30

Summary:
- `np.dot()` (or `np.array.dot()` or `pd.DataFrame.dot()`) performs matrix multiplication, but the results vary depending on the size and the configuration of each array or matrix.

In [46]:
user_matrix.T.shape, shops.shape

((2, 3), (3, 4))

In [47]:
np.dot(user_matrix.T, shops).shape

(2, 4)